### ISSUE TITLE
Creating an expository figure

### ISSUE THREAD

**Issue by jhstern** [jhstern/Assignment-5#1]
In this assignment, I was interested in exploring the relationship between fish sampling location, length, and sex. Because I wanted to see how the distribution of lengths varied among sites and sex, I created this ridgeline plot as my exploratory figure.
<img width="802" alt="exploratory" src="https://user-images.githubusercontent.com/58059867/219912671-11a63dad-54da-40db-a9d3-eafa2129409c.png">

In order to improve the figure, I simplified the plot (removed the separate legend, removed the grid and gray background) and made the colors more accessible. I also added a title and color-coded subtitle, and used more appropriate titles for the axes.
<img width="823" alt="expository" src="https://user-images.githubusercontent.com/58059867/219912693-23b2291a-2dc4-4ab4-80ec-52a3b1f53f64.png">

My full code and process are documented in "Assignment5_figures.pdf", which can be found on this repo in the figures folder or linked below. The exploratory figure is on page 6, and the expository figure is on page 11. 

[Assignment5_figures.pdf](https://github.com/jhstern/Assignment-5/files/10775663/Assignment5_figures.pdf)

**Comment by jhstern** [comment]
[Assignment5_figures.pdf](https://github.com/jhstern/Assignment-5/files/10775662/Assignment5_figures.pdf)

**Comment by mdscheuerell** [comment]
Wow, Jenny! Not only is your expository figure really nice, this issue with your description and embedded figures is really well done as well.

**Comment by jhstern** [comment]
Thank you!
